### ISSUE TITLE
Automower Aspire status change to fault after a while

### ISSUE THREAD

**Issue by Marc1200** [Thomas55555/husqvarna_automower#455]
**Prerequirements**
[ ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
The vacuum.automower_aspire says fault after a while when it's docked, but there isn't a fault.
When the automower finished, it goes back to the docking station. then the status changed in docked.
after a while it says fault(fout) but it hasn't any fault.

**Screenshots**
![image](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/57fe9ef3-0808-4729-8e78-4c27e69511af)
![image](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/2b203057-b23a-4fea-9c93-9ed9af4bf0c0)

**Comment by Thomas55555** [comment]
Can you share the device diagnostics, when the mower is in fault state?

**Comment by Marc1200** [comment]
It looks like that the fault has something to do with GPS coördinates. Because the automower aspire r4 has no gps.
Home assistant is trying to fetch the gps dat with no succeed, then it gives the error in the log 
![Screenshot_20230521-204755](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/7400b602-cd57-47be-8c18-123e28515e5e)
![Screenshot_20230521-204847](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/f35bca65-ebb5-4a74-b7ec-0bf752d49c51)
![Screenshot_20230521-205058](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/1f7c9157-fe7a-43bd-afcf-81f63b5baa92)

**Comment by Marc1200** [comment]
![Screenshot_20230521-204755~2](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/14648324-5dbd-4a89-8bc6-156cc9ddc41b)
![Screenshot_20230521-204847~3](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/e1d3f3e4-76e2-40d8-8163-bc8c440443d2)
![Screenshot_20230521-205007~2](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/4bb449a3-7aaf-424b-ba92-fc4a85606660)
![Screenshot_20230521-205106~2](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/69ebfd0f-fd0e-475b-95b7-1c65ea0cb70a)

**Comment by Marc1200** [comment]
Is it possible to create an option to disable gps function in home assistant?

**Comment by Thomas55555** [comment]
Ah okay. Never thought about an mower without GPS. I think I can do it automatically. But can you share the device diagnostics? You can find it in the integrations overview, when you click on your mower device. That makes it easier to code.

**Comment by Marc1200** [comment]
![Screenshot_20230521-223438](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/2676a631-78d8-4438-a73b-21d00293c6e8)
![Screenshot_20230521-223444](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/300ad10b-48f5-4749-9e8f-62a45208193a)
![Screenshot_20230521-223453](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/42536499-f2bb-42f7-a6c2-65a30a843e0d)
![Screenshot_20230521-223501](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/7fa00a7e-e0eb-48a2-8293-c6dd28e76c98)
![Screenshot_20230521-223514](https://github.com/Thomas55555/husqvarna_automower/assets/68737063/d9a54d33-3957-4778-b1e9-1896890881c1)

**Comment by Thomas55555** [comment]
Can you try the new beta version 2023.5.1b5?
The missing GPS should be fixed. But maybe there are still some other issues

**Comment by Marc1200** [comment]
Sorry, i couldn't add text file on my phone yesterday.
Should i manually copy the new files? 
Normally i update through hacs

**Comment by Thomas55555** [comment]
You can update through hacs. Just activate the button for showing beta versions

**Comment by Marc1200** [comment]
It looks like, it's fixed. Maybe you could also automatically detect if the mower has headlights or nog, when i change headlight it gave me an error also

**Comment by Marc1200** [comment]
Unfortunately, it is not fixed, it gives errors about gps.
Deze fout is ontstaan door een aangepaste integratie.

Logger: aiohttp.server
Source: custom_components/husqvarna_automower/calendar.py:68
Integration: Husqvarna Automower (documentation, issues)
First occurred: 13:43:56 (1 occurrences)
Last logged: 13:43:56

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 542, in get
    calendar_event_list = await entity.async_get_events(
  File "/config/custom_components/husqvarna_automower/calendar.py", line 134, in async_get_events
    return await self.async_get_events_data(hass, start_date, end_date)
  File "/config/custom_components/husqvarna_automower/calendar.py", line 68, in async_get_events_data
    lat = mower_attributes["positions"][0]["latitude"]
IndexError: list index out of range

**Comment by Thomas55555** [comment]
Yes I've fixed this already here #461.
I can also do the headlight stuff the next days.

**Comment by Thomas55555** [comment]
Can you copy the changes of #461 manually for a test, or should I create a new release?

**Comment by Thomas55555** [comment]
Release is out

**Comment by Thomas55555** [comment]
Can you check if in version 2023.5.1b7 the headlight_mode entity is  not generated anymore. It's probably still in your device, but orphaned.

**Comment by Marc1200** [comment]
Yes the headlight mode is gone, i still have status fault sometimes, i cannot see it anymore in the logs

**Comment by Thomas55555** [comment]
Send me the device diagnostics when the mower is in fault mode

**Comment by Marc1200** [comment]
I cannot download the diagnostic now, it won't download
This i see in the logs
Deze fout is ontstaan door een aangepaste integratie.

Logger: aiohttp.server
Source: custom_components/husqvarna_automower/diagnostics.py:25
Integration: Husqvarna Automower (documentation, issues)
First occurred: 16:19:00 (1 occurrences)
Last logged: 16:19:00

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 146, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/diagnostics/__init__.py", line 246, in get
    data = await info.config_entry_diagnostics(hass, config_entry)
  File "/config/custom_components/husqvarna_automower/diagnostics.py", line 25, in async_get_config_entry_diagnostics
    "data_of_all_mowers": async_redact_data(coordinator.data["data"], TO_REDACT),
TypeError: 'NoneType' object is not subscriptable

**Comment by Thomas55555** [comment]
That's strange, because I didn't changed anything there. Can you delete line 14 in the diagnostics.py, restart ha and try it again?

**Comment by Marc1200** [comment]
Yes i did but it doesn't work, it still can't download diagnostics, it says failed

**Comment by Thomas55555** [comment]
Okay. What's the error message?
As an alternative you can turn on debug logging and submit me the part the part which `automower.session` returns.

**Comment by Marc1200** [comment]
Here is a part of the log
[aioautomower log.txt](https://github.com/Thomas55555/husqvarna_automower/files/11548811/aioautomower.log.txt)

**Comment by Marc1200** [comment]
This is what i can see if i check the state and compare it to the same time in the logs

Fault state: 
2023-05-25 14:49:37.622 DEBUG (MainThread) [aioautomower.session] Got status-event, data: {'id': '7f6d468c-3a40-4e2d-87d1-7fb3841a4462', 'type': 'status-event', 'attributes': {'battery': {'batteryPercent': 100}, 'mower': {'mode': 'MAIN_AREA', 'activity': 'PARKED_IN_CS', 'state': 'STOPPED', 'errorCode': 0, 'errorCodeTimestamp': 0}, 'planner': {'nextStartTimestamp': 1685088000000, 'override': {'action': 'IPLANNER_OVERRIDE_ACTION_NOT_ACTIVE'}, 'restrictedReason': 'SENSOR'}, 'metadata': {'connected': True, 'statusTimestamp': 1685018977531}}}

Docked state:
2023-05-25 13:14:12.029 DEBUG (MainThread) [aioautomower.session] Got status-event, data: {'id': '7f6d468c-3a40-4e2d-87d1-7fb3841a4462', 'type': 'status-event', 'attributes': {'battery': {'batteryPercent': 95}, 'mower': {'mode': 'MAIN_AREA', 'activity': 'CHARGING', 'state': 'RESTRICTED', 'errorCode': 0, 'errorCodeTimestamp': 0}, 'planner': {'nextStartTimestamp': 1685021896000, 'override': {'action': 'IPLANNER_OVERRIDE_ACTION_NOT_ACTIVE'}, 'restrictedReason': 'SENSOR'}, 'metadata': {'connected': True, 'statusTimestamp': 1685013251863}}}

**Comment by Marc1200** [comment]
You could maybe check also the activity, because the activity stays the same, parked in cs

**Comment by Thomas55555** [comment]
Hm, I just saw the activity was checked before. So the state in the above example should actually be `docked`
https://github.com/Thomas55555/husqvarna_automower/blob/7fa28854c9b773f570d945ed24b4a9a31fbb30cf/custom_components/husqvarna_automower/vacuum.py#L108

**Comment by Thomas55555** [comment]
But `PARKED_IN_CS` should already return `STATE_DOCKED`. Independently if the mower is stopped or not. So I can't find the problem. But wit the latest beta the download of the diagnostics should work again. Maybe you can download it again, when the mower is in fault mode. Maybe a mistake happend somewhere.

**Comment by Marc1200** [comment]
[config_entry-husqvarna_automower-e5b434b00103e0c37ebc6f85df257e6e.json.txt](https://github.com/Thomas55555/husqvarna_automower/files/11583125/config_entry-husqvarna_automower-e5b434b00103e0c37ebc6f85df257e6e.json.txt)

**Comment by Marc1200** [comment]
The problem is still not fixed, with the beta 8 version it still gives sometimes a fault when the mower is at the docking station

**Comment by Thomas55555** [comment]
In what state was the mower, when you created the diagnostics file?
Because in this time, it was not `PARKED_IN_CS` but the activity was `NOT_APPLICABLE`.
And I can't just track weather the state is `STOPPED`, according to the docs (https://developer.husqvarnagroup.cloud/apis/automower-connect-api#openapi), stopped is more like an error:
`STOPPED - Mower is stopped, and cannot be started remotely. Start requirements (safety or other) are not fulfilled.`

**Comment by Marc1200** [comment]
[Log 01-06-2023.txt](https://github.com/Thomas55555/husqvarna_automower/files/11623517/Log.01-06-2023.txt)

at the time of 6:49 it changed into fault. see the log. maybe because it still tries to do an "get position" event?

**Comment by Thomas55555** [comment]
No. It's just because of the state `STOPPED` 
Did the mower stated working again, without that you did anything at the mower?

**Comment by Marc1200** [comment]
Yes after an hour of 2 it change back to docked or when the mower starts with mowing schedule, do you need all logs of today?

**Comment by Thomas55555** [comment]
No. I'll write an email to Husqvarna the next days and ask them for support.

**Comment by Marc1200** [comment]
With update 2023.6.1 beta the fault is unfortunately not gone.

**Comment by Thomas55555** [comment]
Yes. I didn't changed anything regarding this. But I wrote an email to Husqvarna yesterday and asked for support.

**Comment by Thomas55555** [comment]
I've an answer from Husqvarna now. This is an known bug with this mower. There will be an firmware update for your mower in two weeks, which fixes the bug. After installing the FOTS update, it should work.
Let me know the result.

**Comment by Marc1200** [comment]
Okay, i wait until then and let you know, thanks for your effort

**Comment by Marc1200** [comment]
We installed the new firmware update for the mower last friday.
Now the mower stays docked, there is no fault anymore in home assistant, only if there is a real fault.
Thanks for your effort!
